In [3]:
import pandas as pd
import numpy as np

In [4]:
# Import the raw dataset again
df = pd.read_excel("Dry.xlsx")

# Display the first 5 rows
df.head()

,Segment>>,Consumer,Unnamed: 2,Unnamed: 3,Unnamed: 4,Consumer Total,Corporate,Unnamed: 7,Unnamed: 8,Unnamed: 9,Corporate Total,Home Office,Unnamed: 12,Unnamed: 13,Unnamed: 14,Home Office Total
0,Ship Mode>>,First Class,Same Day,Second Class,Standard Class,NaN,First Class,Same Day,Second Class,Standard Class,NaN,First Class,Same Day,Second Class,Standard Class,NaN
1,Order ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056,91.056
3,CA-2011-100706,NaN,NaN,129.44,NaN,129.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CA-2011-100895,NaN,NaN,NaN,605.47,605.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(825, 16)

In [6]:
df.columns

Index(['Segment>>', 'Consumer', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Consumer Total', 'Corporate', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Corporate Total', 'Home Office', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Home Office Total'],
      dtype='object')

In [7]:
df.head(3).T

                                0         1               2
Segment>>             Ship Mode>>  Order ID  CA-2011-100293
Consumer              First Class       NaN             NaN
Unnamed: 2               Same Day       NaN             NaN
Unnamed: 3           Second Class       NaN             NaN
Unnamed: 4         Standard Class       NaN             NaN
Consumer Total                NaN       NaN             NaN
Corporate             First Class       NaN             NaN
Unnamed: 7               Same Day       NaN             NaN
Unnamed: 8           Second Class       NaN             NaN
Unnamed: 9         Standard Class       NaN             NaN
Corporate Total               NaN       NaN             NaN
Home Office           First Class       NaN             NaN
Unnamed: 12              Same Day       NaN             NaN
Unnamed: 13          Second Class       NaN             NaN
Unnamed: 14        Standard Class       NaN          91.056
Home Office Total             NaN       NaN          91.056

In [8]:
df.iloc[2:7]

,Segment>>,Consumer,Unnamed: 2,Unnamed: 3,Unnamed: 4,Consumer Total,Corporate,Unnamed: 7,Unnamed: 8,Unnamed: 9,Corporate Total,Home Office,Unnamed: 12,Unnamed: 13,Unnamed: 14,Home Office Total
2,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056,91.056
3,CA-2011-100706,NaN,NaN,129.44,NaN,129.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CA-2011-100895,NaN,NaN,NaN,605.47,605.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CA-2011-100916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.86,788.86,NaN,NaN,NaN,NaN,NaN
6,CA-2011-101266,NaN,NaN,13.36,NaN,13.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Define the Segment and Ship Mode for each sales column
column_mapping = {
    "Consumer": {
        "First Class": "Consumer",
        "Same Day": "Unnamed: 2",
        "Second Class": "Unnamed: 3",
        "Standard Class": "Unnamed: 4"
    },
    "Corporate": {
        "First Class": "Corporate",
        "Same Day": "Unnamed: 7",
        "Second Class": "Unnamed: 8",
        "Standard Class": "Unnamed: 9"
    },
    "Home Office": {
        "First Class": "Home Office",
        "Same Day": "Unnamed: 12",
        "Second Class": "Unnamed: 13",
        "Standard Class": "Unnamed: 14"
    }
}
Wait — one

SyntaxError: invalid character '—' (U+2014) (1307310483.py, line 22)

In [10]:
# Identify the 12 actual Segment × Ship Mode sales columns
sales_columns = df.columns[[1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14]]

sales_columns

Index(['Consumer', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Corporate',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Home Office', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [11]:
segment_shipmode = {
    "Consumer": ("Consumer", "First Class"),
    "Unnamed: 2": ("Consumer", "Same Day"),
    "Unnamed: 3": ("Consumer", "Second Class"),
    "Unnamed: 4": ("Consumer", "Standard Class"),
    
    "Corporate": ("Corporate", "First Class"),
    "Unnamed: 7": ("Corporate", "Same Day"),
    "Unnamed: 8": ("Corporate", "Second Class"),
    "Unnamed: 9": ("Corporate", "Standard Class"),
    
    "Home Office": ("Home Office", "First Class"),
    "Unnamed: 12": ("Home Office", "Same Day"),
    "Unnamed: 13": ("Home Office", "Second Class"),
    "Unnamed: 14": ("Home Office", "Standard Class")
}

segment_shipmode

{'Consumer': ('Consumer', 'First Class'),
 'Unnamed: 2': ('Consumer', 'Same Day'),
 'Unnamed: 3': ('Consumer', 'Second Class'),
 'Unnamed: 4': ('Consumer', 'Standard Class'),
 'Corporate': ('Corporate', 'First Class'),
 'Unnamed: 7': ('Corporate', 'Same Day'),
 'Unnamed: 8': ('Corporate', 'Second Class'),
 'Unnamed: 9': ('Corporate', 'Standard Class'),
 'Home Office': ('Home Office', 'First Class'),
 'Unnamed: 12': ('Home Office', 'Same Day'),
 'Unnamed: 13': ('Home Office', 'Second Class'),
 'Unnamed: 14': ('Home Office', 'Standard Class')}

In [12]:
records = []

for column, (segment, ship_mode) in segment_shipmode.items():
    temp = df[["Segment>>", column]].copy()
    temp.columns = ["OrderID", "Sales"]
    
    temp["Segment"] = segment
    temp["Ship Mode"] = ship_mode
    
    records.append(temp)

long_df = pd.concat(records, ignore_index=True)

long_df = long_df[["Segment", "Ship Mode", "OrderID", "Sales"]]

In [13]:
long_df.head(10)

    Segment    Ship Mode         OrderID        Sales
0  Consumer  First Class     Ship Mode>>  First Class
1  Consumer  First Class        Order ID          NaN
2  Consumer  First Class  CA-2011-100293          NaN
3  Consumer  First Class  CA-2011-100706          NaN
4  Consumer  First Class  CA-2011-100895          NaN
5  Consumer  First Class  CA-2011-100916          NaN
6  Consumer  First Class  CA-2011-101266          NaN
7  Consumer  First Class  CA-2011-101560          NaN
8  Consumer  First Class  CA-2011-101770          NaN
9  Consumer  First Class  CA-2011-102274          NaN

In [14]:
df_data = df.iloc[2:].reset_index(drop=True)

In [15]:
df_data.head()

,Segment>>,Consumer,Unnamed: 2,Unnamed: 3,Unnamed: 4,Consumer Total,Corporate,Unnamed: 7,Unnamed: 8,Unnamed: 9,Corporate Total,Home Office,Unnamed: 12,Unnamed: 13,Unnamed: 14,Home Office Total
0,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056,91.056
1,CA-2011-100706,NaN,NaN,129.44,NaN,129.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,NaN,NaN,NaN,605.47,605.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA-2011-100916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.86,788.86,NaN,NaN,NaN,NaN,NaN
4,CA-2011-101266,NaN,NaN,13.36,NaN,13.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
records = []

for column, (segment, ship_mode) in segment_shipmode.items():
    temp = df_data[["Segment>>", column]].copy()
    temp.columns = ["OrderID", "Sales"]
    
    temp["Segment"] = segment
    temp["Ship Mode"] = ship_mode
    
    records.append(temp)

long_df = pd.concat(records, ignore_index=True)

long_df = long_df[["Segment", "Ship Mode", "OrderID", "Sales"]]

In [17]:
long_df.head(10)

    Segment    Ship Mode         OrderID Sales
0  Consumer  First Class  CA-2011-100293   NaN
1  Consumer  First Class  CA-2011-100706   NaN
2  Consumer  First Class  CA-2011-100895   NaN
3  Consumer  First Class  CA-2011-100916   NaN
4  Consumer  First Class  CA-2011-101266   NaN
5  Consumer  First Class  CA-2011-101560   NaN
6  Consumer  First Class  CA-2011-101770   NaN
7  Consumer  First Class  CA-2011-102274   NaN
8  Consumer  First Class  CA-2011-102673   NaN
9  Consumer  First Class  CA-2011-102988   NaN

In [18]:
long_df[long_df["Sales"].notna()].head(10)

      Segment    Ship Mode         OrderID    Sales
11   Consumer  First Class  CA-2011-103366   149.95
20   Consumer  First Class  CA-2011-109043    243.6
29   Consumer  First Class  CA-2011-113166    9.568
51   Consumer  First Class  CA-2011-124023     8.96
63   Consumer  First Class  CA-2011-130155     34.2
76   Consumer  First Class  CA-2011-136861   31.984
104  Consumer  First Class  CA-2011-153927   286.65
113  Consumer  First Class  CA-2011-157784   514.03
119  Consumer  First Class  CA-2011-160094  1000.95
128  Consumer  First Class  CA-2011-164749    9.912

In [19]:
long_df.shape

(9876, 4)

In [20]:
long_df["Sales"].notna().sum()

np.int64(834)

In [21]:
long_df["Sales"].isna().sum()

np.int64(9042)

In [22]:
long_df[long_df["OrderID"] == "Grand Total"]

          Segment       Ship Mode      OrderID        Sales
822      Consumer     First Class  Grand Total    20802.173
1645     Consumer        Same Day  Grand Total     8132.409
2468     Consumer    Second Class  Grand Total   49724.2545
3291     Consumer  Standard Class  Grand Total  116922.1345
4114    Corporate     First Class  Grand Total    20792.607
4937    Corporate        Same Day  Grand Total     9907.308
5760    Corporate    Second Class  Grand Total    35243.231
6583    Corporate  Standard Class  Grand Total   55942.7865
7406  Home Office     First Class  Grand Total     7737.786
8229  Home Office        Same Day  Grand Total     2977.456
9052  Home Office    Second Class  Grand Total     8791.127
9875  Home Office  Standard Class  Grand Total   54748.6325

In [23]:
long_df = long_df[long_df["OrderID"] != "Grand Total"].reset_index(drop=True)

In [24]:
long_df.shape

(9864, 4)

In [25]:
long_df[long_df["OrderID"] == "Grand Total"]

Empty DataFrame
Columns: [Segment, Ship Mode, OrderID, Sales]
Index: []

In [27]:
# Keep only records with actual sales values
long_df = long_df.dropna(subset=["Sales"]).reset_index(drop=True)

In [28]:
long_df.shape

(822, 4)

In [29]:
long_df.head(20)

     Segment    Ship Mode         OrderID    Sales
0   Consumer  First Class  CA-2011-103366   149.95
1   Consumer  First Class  CA-2011-109043    243.6
2   Consumer  First Class  CA-2011-113166    9.568
3   Consumer  First Class  CA-2011-124023     8.96
4   Consumer  First Class  CA-2011-130155     34.2
5   Consumer  First Class  CA-2011-136861   31.984
6   Consumer  First Class  CA-2011-153927   286.65
7   Consumer  First Class  CA-2011-157784   514.03
8   Consumer  First Class  CA-2011-160094  1000.95
9   Consumer  First Class  CA-2011-164749    9.912
10  Consumer  First Class  CA-2011-166730   39.128
11  Consumer  First Class  CA-2012-102722    106.5
12  Consumer  First Class  CA-2012-102778   18.176
13  Consumer  First Class  CA-2012-117828   194.32
14  Consumer  First Class  CA-2012-130218    59.48
15  Consumer  First Class  CA-2012-132318   182.91
16  Consumer  First Class  CA-2012-137974   2298.9
17  Consumer  First Class  CA-2012-138625   197.72
18  Consumer  First Class  CA-2012-141327  440.144
19  Consumer  First Class  CA-2012-149300   32.985

In [30]:
long_df.shape

(822, 4)

In [31]:
# Save the final cleaned dataset
long_df.to_excel("Clean_1.xlsx", index=False)

In [32]:
import os

os.path.exists("Clean_1.xlsx")

True